### ISSUE TITLE
taskA.py

### ISSUE THREAD

**Issue by faramer86** [faramer86/BIOPYTHON_ITMO_2018#9]
Done! If everything is fine I will add arguments using argparse.

**Comment by YakutovDmitriy** [comment]
You didn't fixed some critical issues in `task9`, so I don't know how it can work)
I tries to execute it but I have and IndexError here: `user_name = cwd.get_path_name().split('/')[2]`
* Why do you think that your path contain `user_name`?
* Also your path can contain less than 3 parts after splitting it by `/`
* And I have windows, so my path contain no symbols `/`. Use `os.sep` instead

**Comment by faramer86** [comment]
Done! I used `os.path.join`. Does it works?

**Comment by YakutovDmitriy** [comment]
Hm-m-m, I still see a line `user_name = cwd.get_path_name().split('/')[2]`. Are you sure you fixed and commited it?

**Comment by faramer86** [comment]
Yes. I just forgot remove this variable.

**Comment by YakutovDmitriy** [comment]
* `cat`, `head` and `tail`. You print extra empty lines between lines of file
* You check if `new_name` is directory and `old_name` is file in `mv`. And in this case you move file in that directory. Thats good. I guess you want to do the same in `cp`

**Comment by faramer86** [comment]
Done!

**Comment by YakutovDmitriy** [comment]
* `cat`, `head` and `tail` are ok now
